schema_version: 1

context:
  version: 0.10.1

package:
  name: ttp
  version: ${{ version }}

source:
- url: https://files.pythonhosted.org/packages/source/t/ttp/ttp-${{ version }}.tar.gz
  sha256: 9c928aeb1f2dade05419c7ecc756d62cb45857deb5cc6b1b9f2058e70f25ae59

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - ttp = ttp.ttp:cli_tool

requirements:
  host:
    - python ${{ python_min }}.*,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=${{ python_min }},<4.0

tests:
  - python:
      imports:
        - ttp
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - '*'
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - ttp --help

about:
  summary: Template Text Parser
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/dmulyalin/ttp

extra:
  recipe-maintainers:
    - cousinbr
    - jsmolic
